CREATE DATABASE cyclecare;

\c cyclecare;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE calendarios_ciclo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE ciclo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sintoma VARCHAR(255),
    fluxo VARCHAR(50) NOT NULL,
    observacao TEXT,
    calendario_ciclo_id BIGINT NOT NULL,
    FOREIGN KEY (calendario_ciclo_id) REFERENCES calendarios_ciclo(id) ON DELETE CASCADE
);
