CREATE DATABASE cyclecare;

\c cyclecare;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE ciclo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sintoma VARCHAR(255),
    fluxo VARCHAR(50) NOT NULL,
    observacao TEXT,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE eventos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255),
    descricao TEXT,
    data_hora_inicio DATE,
    data_hora_fim DATE,
    ciclo_id BIGINT NOT NULL,
    CONSTRAINT fk_eventos_ciclo
        FOREIGN KEY (ciclo_id)
        REFERENCES ciclos(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
