CREATE TABLE ciclo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sintoma VARCHAR(255),
    fluxo VARCHAR(50) NOT NULL,
    observacao TEXT,
    calendario_ciclo_id BIGINT NOT NULL,
    FOREIGN KEY (calendario_ciclo_id) REFERENCES calendarios_ciclo(id) ON DELETE CASCADE
);
