CREATE TABLE ciclo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sintoma VARCHAR(255),
    fluxo VARCHAR(50) NOT NULL,
    observacao TEXT,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
